/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.practical1.frontend.paneles_tabla;

/**
 *
 * @author rafael-cayax
 */
public class PanelInformacion extends javax.swing.JPanel {

    /**
     * Creates new form panelPrueba
     */
    public PanelInformacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        informacionLabel = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setLayout(new java.awt.GridBagLayout());

        informacionLabel.setText("jLabel1");
        add(informacionLabel, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents
    
    public void informar(String texto){
        informacionLabel.setText(texto);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel informacionLabel;
    // End of variables declaration//GEN-END:variables
}
