/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.practical1.frontend.paneles_tabla;

import java.awt.Color;
import javax.swing.Icon;

/**
 *
 * @author rafael-cayax
 */
public class PanelCuadro extends javax.swing.JPanel {

    /**
     * Creates new form panelCuadro
     */
    public PanelCuadro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        fila = new javax.swing.JLabel();
        columna = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        colorB = new javax.swing.JLabel();
        colorDecode = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setMaximumSize(new java.awt.Dimension(250, 100));
        setMinimumSize(new java.awt.Dimension(250, 100));
        setPreferredSize(new java.awt.Dimension(250, 100));
        setLayout(new java.awt.GridBagLayout());

        fila.setText("Fila : 0");
        add(fila, new java.awt.GridBagConstraints());

        columna.setText("Col: 0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        add(columna, gridBagConstraints);

        jLabel3.setText("Color: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        add(jLabel3, gridBagConstraints);

        colorB.setBackground(new java.awt.Color(255, 51, 0));
        colorB.setToolTipText("");
        colorB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        colorB.setOpaque(true);
        colorB.setPreferredSize(new java.awt.Dimension(18, 18));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 20);
        add(colorB, gridBagConstraints);

        colorDecode.setText("#color");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        add(colorDecode, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    public void informacionCuadro(String fila, String columna, String color){
        this.fila.setText("Fila: " + fila);
        this.columna.setText("Col: " + columna);
        Color color2 = Color.decode(color);
        colorB.setBackground(color2);
        colorB.repaint();
        colorDecode.setText(color);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel colorB;
    private javax.swing.JLabel colorDecode;
    private javax.swing.JLabel columna;
    private javax.swing.JLabel fila;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
